version: "3.9"

services:
  web:
    build: . 
    ports:
      - "8080:8080"
      - "8888:8888"
    depends_on:
      - mongo
      - jaeger
    networks:
      - mynetwork
    env_file:
      - .env 
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
     - mynetwork
  jaeger:
    image: jaegertracing/all-in-one:1.35
    environment:
      - OLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "4317:4317"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
     - mynetwork
networks:
  mynetwork:
    driver: bridge